apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1                       # how many instances to run
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: mydjangoapp:latest  # matches your local Docker build
          imagePullPolicy: Never     # use local image built inside Minikube
          ports:
            - containerPort: 8000    # Djangoâ€™s default port
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: website.settings
            - name: DJANGO_ALLOWED_HOSTS
              value: "localhost,127.0.0.1,192.168.49.2"
